# Generated by Django 4.1.7 on 2023-04-03 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('App', 'Appetizer'), ('En', 'Entree'), ('D', 'Dessert'), ('Bev', 'Beverage'), ('S', 'Side'), ('Ba', 'Baked Good')], default='dessert', max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='img_url',
            field=models.URLField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
