# Generated by Django 4.1.7 on 2023-04-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_recipe_category_alter_recipe_img_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='calories',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='price',
            field=models.DecimalField(max_digits=5, decimal_places=2, default=1.00),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('Appetizer', 'Appetizer'), ('Entree', 'Entree'), ('Dessert', 'Dessert'), ('Beverage', 'Beverage'), ('Side', 'Side'), ('Baked Good', 'Baked Good')], default='App', max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='day_of_week',
            field=models.CharField(choices=[('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('Th', 'Thursday'), ('F', 'Friday'), ('Sa', 'Saturday'), ('S', 'Sunday')], default='M', max_length=20),
        ),
    ]
