# Generated by Django 4.1.7 on 2023-04-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_recipe_day_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('Appetizer', 'Appetizer'), ('Entree', 'Entree'), ('Dessert', 'Dessert'), ('Beverage', 'Beverage'), ('Side', 'Side'), ('Baked Good', 'Baked Good')], default='App', max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='day_of_week',
            field=models.CharField(choices=[('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('Th', 'Thursday'), ('F', 'Friday'), ('Sa', 'Saturday'), ('S', 'Sunday')], default='M', max_length=255),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='img_url',
            field=models.URLField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(default='GABAGOOL', max_length=100),
        ),
    ]
