# Generated by Django 4.1.7 on 2023-04-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_recipe_category_alter_recipe_day_of_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='day_of_week',
            field=models.CharField(max_length=255),
        ),
    ]
