# Generated by Django 4.1.7 on 2023-04-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_recipe_day_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(default='App', max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='day_of_week',
            field=models.CharField(default='Monday', max_length=255),
        ),
    ]
