# Generated by Django 4.1.7 on 2023-04-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_recipe_category_alter_recipe_day_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('Appetizer', 'Appetizer'), ('Entree', 'Entree'), ('Dessert', 'Dessert'), ('Beverage', 'Beverage'), ('Side', 'Side'), ('Baked Good', 'Baked Good')], default='App', max_length=100),
        ),
    ]
