# Generated by Django 4.1.7 on 2023-04-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_recipe_instructions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='img_url',
            field=models.URLField(default='https://i.pinimg.com/originals/f4/3d/55/f43d55d69d9e8f11ce20a79277cdfafc.jpg', max_length=300),
        ),
    ]
